TESTS = $(wildcard ./*.bin)

# you should not need this.
# TTYUSB = 

# can swap these around to make sure hw is working.
BOOTLOADER = pi-install
BOOTLOADER = my-install

# so we don't lose simple_boot
EXCLUDE := cat

include $(CS140E_2024_PATH)/libpi/mk/Makefile.check-v3
