# need the makefile to give an error if this doesn't exist
PROGS := timer.c
COMMON_SRC := interrupts-c.c	timer-interrupt.c interrupts-asm.S

# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install
RUN = 1

include $(CS140E_2024_PATH)/libpi/mk/Makefile.template-v4
# include $(CS140E_2024_PATH)/libpi/mk/Makefile.simple
