TESTS = $(wildcard ./*.bin)
# you should not need this.
# TTYUSB = 
BOOTLOADER = my-install

# we only look at this output
GREP_STR := "TRACE:"

include $(CS140E_2024_PATH)/libpi/mk/Makefile.check-v2
