# need the makefile to give an error if this doesn't exist
PROGS := todo-test.c
COMMON_SRC := todo-asm.S

# uncomment if you want it to automatically run.
RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
