# need the makefile to give an error if this doesn't exist
PROGS := measure.c cycles-per-sec.c mode.c
COMMON_SRC :=

# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install
RUN = 1

include $(CS140E_2024_PATH)/libpi/mk/Makefile.template-v4
# include $(CS140E_2024_PATH)/libpi/mk/Makefile.simple
