# list out the driver program source 
PROGS = cycles-per-sec.c

# pick one of your attachment points (first or last) consistently.
BOOTLOADER = my-install

OPT_LEVEL = -O3

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

LIB_POST = $(CS140E_2024_PATH)/lib/libgcc.a

DEPS = ./Makefile
include $(CS140E_2024_PATH)/libpi/mk/Makefile.template-fixed
