PROGS := test-mbox.c
COMMON_SRC := mbox.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

include $(CS140E_2024_PATH)/libpi/mk/Makefile.template
