# work through these in order.
PROGS += 1-stack-dir.c
# PROGS += 2-where-push.c
# PROGS += 3-push-order.c
# PROGS += 4-callee.c
# PROGS += 5-write-regs.c

# most of the code you'll implement in here.
COMMON_SRC = asm-checks.S

# run them all
# PROGS = $(wildcard ./[12345]*.c)


# uncomment if you want it to automatically run.
RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

include $(CS140E_2024_PATH)/libpi/mk/Makefile.template-fixed
