PROGS = logic-analyzer.c
STAFF_OBJS += $(CS140E_2024_PATH)/libpi/staff-objs/sw-uart.o
STAFF_OBJS += $(CS140E_2024_PATH)/libpi/staff-objs/interrupts-asm.o
STAFF_OBJS += $(CS140E_2024_PATH)/libpi/staff-objs/interrupts-vec-asm.o

# if you want to use our libpi
# LPI = ../staff-objs/libpi.a

# automatically run the code
RUN = 0

# if you need to override the install
BOOTLOADER = my-install

include $(CS140E_2024_PATH)/libpi/mk/Makefile.template-fixed
